#!/usr/bin/env python

from __future__ import print_function
""" Add the line file and line of string occurrence to specified dictionary CRAZY"""

for thing in range(1, 25):  # comment here CRAZY
	print("test number {}".format(thing))  # Other comment thing here
	print("MORE CRAZY")  # CRAZY comment
	print("also CRAZY")  # crazy
	print("little crazy")





